# Generated by Django 3.2.9 on 2023-08-05 07:29

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название статьи')),
                ('img', models.ImageField(upload_to='', verbose_name='Иконка')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Контент статьи')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название категории')),
                ('img', models.ImageField(upload_to='', verbose_name='Иконка')),
                ('slug', models.SlugField(max_length=101, unique=True, verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название услуги')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Слаг')),
                ('img', models.ImageField(upload_to='', verbose_name='Иконка')),
                ('quantity', models.CharField(blank=True, help_text='Например: 1 тыс. - 900 тыс.', max_length=60, null=True, verbose_name='Количество накрутки (от и до)')),
                ('warranty', models.CharField(blank=True, help_text='Например: 12 мес.', max_length=50, null=True, verbose_name='Гарантия')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Описание')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='mainapp.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
    ]
